import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Banner from "./component/Banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full w-full flex">
          <Banner className="w-[0] lg:w-[50%]"></Banner>
          <div className="w-[100%] h-full bg-[#5483E8] lg:w-[50%]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
