name: client-deploy

on:
  push:
    branches: [ "fe_develop" ]
    paths:
      - client/**
      - .github/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-front:
    name: Client Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Npm Install
        run: npm ci

      - name: Project Build
        run: npm run build

      - name: Upload To S3
        run: aws s3 sync --region ${{ secrets.AWS_REGION }} ./dist s3://${{ secrets.S3_BUCKET_DEVELOP_NAME }} --delete
