name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    paths:
      - server/**
      - .github/**

permissions:
  contents: read

env:
  S3_BUCKET_NAME: indiego-bucket

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - uses: actions/upload-artifact@v2
        with:
          name: applicaiton.yml
          path: ./src/main/resources/application.yml

      - name: Add permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          build-root-directory: ./server

      - name: Make zip file
        run: zip -r ./indiego-deploy.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCT_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PRODUCT_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 압축한 프로젝트를 S3로 전송합니다.
      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./indiego-deploy.zip s3://${{ secrets.PRODUCT_S3_BUCKET_NAME }}/indiego-deploy.zip

      # CodeDeploy에게 배포 명령을 내립니다.
      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name ${{ secrets.CODE_DEPLOY_PRODUCT_APPLICATION_NAME }}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ secrets.CODE_DEPLOY_PRODUCT_DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=indiego-deploy.zip
      # indiego         ${{ secrets.CODE_DEPLOY_PRODUCT_APPLICATION_NAME }}
      # indiego-group   ${{ secrets.CODE_DEPLOY_PRODUCT_DEPLOYMENT_GROUP_NAME }}
      # indiego-bucket  ${{ secrets.S3_BUCKET_NAME }}
